# Generated by Django 5.1.2 on 2024-10-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default=None, upload_to='covers/'),
        ),
    ]
